services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  global:
    - URL=http://localhost:8080
    - PORT=8080
language: node_js
node_js:
 - "10"
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm test
after_sucess:
  - npm run coverall