services:
  - postgresql
addons:
  postgresql: "12.0"
env:
  global:
    - URL=http://localhost:8080
    - PORT=8080
language: node_js
node_js:
 - "10"
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm test
after_sucess:
  - npm run coverall